### PR TITLE
Navigation/Input

### PR DESCRIPTION
**Pull request by jakub2787**
I have already made this input and added a hover to NavLink, let me know if the colour can be because there was none in the Figma and I was supposed to add it.

### CODE REVIEW

**Comment by maram-9** [comment]
For me looks good!

**Comment by maram-9** [comment]
I guest, NavLink has color white. I will try white :)

**Comment by jakub2787** [comment]
NavLink has a white color before hover.

**Comment by KarolinaJ33** [comment]
In the theme.js I see a double color: #7E839A as darkerGrey and waterloo.
About NavLink I think that is ok :)

**Review by KarolinaJ33 — APPROVED** [review]

**Comment by jakub2787** [comment]
I don't see a duplicate color anywhere in theme.js, now I just noticed that I removed the color from the theme by accident.

**Pull request merged**
