### PR TITLE
created peopleList with API

### PR DESCRIPTION
**Pull request by maram-9**
I created peopleList with API. Pagination is only for graphics - it doesn't work yet. Nice lecture!

### CODE REVIEW

**Comment by jakub2787** [comment]
Why did you change the error const to export const in the component if you changed to export const then it seems to me that you should remove export default then. Besides that, good job.

**Comment by maram-9** [comment]
Hi @jakub2787 ! Yes, you have right. I made mistake. Now is corret.

**Comment by maram-9** [comment]
I added personPage to. Movie cast isn't complete.

**Comment by jakub2787** [comment]
Okay now it's fine

**Review by jakub2787 — APPROVED** [review]

**Pull request merged**
